#!/bin/sh
# generate-helplinks-nginx.sh
# Converts helpmap/_redirects into Nginx location directives.
# Run on the docs VPS after CI copies both files there (see .github/workflows/deploy-helplinks.yml).
# Usage: ./generate-helplinks-nginx.sh [redirects-file] [output-file]
#
# Design doc: dev/wiki.js/static-link-redirect-architecture.md
# Build/deploy runbook: docs/subsystems/documentation/SL-2-helplinks-cicd.md (codenforce repo)

set -eu

REDIRECTS="${1:-helpmap/_redirects}"
OUTFILE="${2:-/etc/nginx/snippets/helplinks.conf}"
BASE="https://docs.codenforce.org"

printf '# Auto-generated by CI on %s — do not edit manually\n' "$(date -u)" > "$OUTFILE"

# Skip comment lines (including "# TODO ..." unassigned entries — those fall through to the
# catch-all `location /help/ { return 302 .../; }` block in the Nginx site config) and blank
# lines. Each remaining line is "stable-id  target-path" — read splits it on whitespace.
grep -v '^#' "$REDIRECTS" | grep -v '^[[:space:]]*$' | while read -r id target; do
    printf 'location = /help/%s { return 302 %s%s; }\n' "$id" "$BASE" "$target" >> "$OUTFILE"
done

nginx -t && systemctl reload nginx
